### PR TITLE
Fix kafka consumer OpenInbound loop

### LINKED ISSUE #591: Kafka consumer is constantly being terminated without an error
We're considering adopting cloud events for asynchornous message processing using Kafka. However, during our POC we've ran into an issue, which causes the consumer to be constantly terminated. `client.StartReceive(ctx, receive)` simply returns `nil` after roughly 3 minutes. Here are the relevant logs:

```
todd@Todds-MacBook-Pro marketo-service % KAFKA_BROKERS="172.20.46.141:9092" KAFKA_PREFIX="todd2-" KAFKA_TOPIC="events" KAFKA_CONSUMER_GROUP="todd2" ./dist/marketo-service
marketo-service2020/09/28 19:28:37 client.go:133: Initializing new client
marketo-service2020/09/28 19:28:37 config.go:544: ClientID is the default of 'sarama', you should consider setting it to something application-specific.
marketo-service2020/09/28 19:28:37 config.go:544: ClientID is the default of 'sarama', you should consider setting it to something application-specific.
marketo-service2020/09/28 19:28:37 client.go:841: client/metadata fetching metadata for all topics from broker 172.20.46.141:9092
marketo-service2020/09/28 19:28:38 broker.go:209: Connected to broker at 172.20.46.141:9092 (unregistered)
marketo-service2020/09/28 19:28:38 client.go:572: client/brokers registered new broker #0 at kafka-kafka-0.kafka-kafka-brokers.kafka.svc:9092
marketo-service2020/09/28 19:28:38 client.go:572: client/brokers registered new broker #2 at kafka-kafka-2.kafka-kafka-brokers.kafka.svc:9092
marketo-service2020/09/28 19:28:38 client.go:572: client/brokers registered new broker #1 at kafka-kafka-1.kafka-kafka-brokers.kafka.svc:9092
marketo-service2020/09/28 19:28:38 client.go:180: Successfully initialized new client
marketo-service2020/09/28 19:28:38 client.go:838: client/metadata fetching metadata for [todd2-events] from broker 172.20.46.141:9092
marketo-service2020/09/28 19:28:38 client.go:1005: client/coordinator requesting coordinator for consumergroup todd2 from 172.20.46.141:9092
marketo-service2020/09/28 19:28:39 client.go:1028: client/coordinator coordinator for consumergroup todd2 is #2 (kafka-kafka-2.kafka-kafka-brokers.kafka.svc:9092)
marketo-service2020/09/28 19:28:39 config.go:544: ClientID is the default of 'sarama', you should consider setting it to something application-specific.
marketo-service2020/09/28 19:28:39 broker.go:207: Connected to broker at kafka-kafka-2.kafka-kafka-brokers.kafka.svc:9092 (registered as #2)
marketo-service2020/09/28 19:28:42 client.go:1005: client/coordinator requesting coordinator for consumergroup todd2 from 172.20.46.141:9092
marketo-service2020/09/28 19:28:43 client.go:1028: client/coordinator coordinator for consumergroup todd2 is #2 (kafka-kafka-2.kafka-kafka-brokers.kafka.svc:9092)
marketo-service2020/09/28 19:28:43 config.go:544: ClientID is the default of 'sarama', you should consider setting it to something application-specific.
marketo-service2020/09/28 19:28:43 broker.go:207: Connected to broker at kafka-kafka-0.kafka-kafka-brokers.kafka.svc:9092 (registered as #0)
marketo-service2020/09/28 19:28:43 consumer.go:801: consumer/broker/0 added subscription to todd2-events/0
2020/09/28 19:28:44 Received event Validation: valid
Context Attributes,
  specversion: 1.0
  type: users:delete
  source: shoreline
  id: 9d3b2e56-55da-41ab-844a-0bffe29c5836
  time: 2020-09-28T16:27:58.238284Z
  datacontenttype: application/json
Data,
  {
    "userid": "1234567890",
    ...
  }

marketo-service2020/09/28 19:29:55 consumer_group.go:426: kafka server: Request was for a consumer group that is not coordinated by this broker.
marketo-service2020/09/28 19:29:55 consumer_group.go:466: loop check partition number coroutine will exit, topics [todd2-events]
marketo-service2020/09/28 19:29:55 consumer.go:807: consumer/broker/0 closed dead subscription to todd2-events/0
marketo-service2020/09/28 19:29:55 client.go:232: Closing Client
2020/09/28 19:29:55 Consumer stopped
```

The receive function just logs the received event and returns `protocol.ResultACK`. The behavior doesn't change even if we don't return a result from the function.

I suspect that the offsets are not being committed, because when we restart the receiver, it starts from the beginning of the topic as if there are no committed offsets (`saramaConfig.Consumer.Offsets.Initial = sarama.OffsetOldest`). If this is true, we might be running into https://github.com/Shopify/sarama/issues/1608.

Could you please advise what to do?

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Fix #591

Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

### CODE REVIEW

File: protocol/kafka_sarama/v2/receiver.go [hunk 1]
```diff
@@ -152,7 +152,9 @@ func (c *Consumer) startConsumerGroupLoop(cg sarama.ConsumerGroup, ctx context.C
 			return
 		// Something else happened
 		default:
-			if err == nil || err == sarama.ErrClosedClient || err == sarama.ErrClosedConsumerGroup {
+			if err == nil {
```
Comment (toddkazakov) [inline protocol/kafka_sarama/v2/receiver.go:155]: When rebalance is about to happen and this condition is `true`, sarama will invoke `receiver.Cleanup()` which will close the incoming channel. I believe this will cause panic when new messages are consumed. I'm quite new to sarama, so I can't suggest a working solution at the moment.

**Comment by slinkydeveloper** [comment]
Ok so this should fix it, but it adds a breaking change because now `Receiver` is `Closer`.

Now the incoming channel is not closed anymore from the session, but a manual method is invoked to cleanup that channel. @n3wscott mind taking a look? I tried to write a test for it, but it's quite hard without scrambling some prod code too

**Review by n3wscott — APPROVED** [review]
LGTM

**Comment by slinkydeveloper** [comment]
@toddkazakov I'm gonna merge it, let me know if it solves the issue
