### PR TITLE
fix: make send subject optional via context

### LINKED ISSUE #1115: Why so inconvenient protocol binding for NATS?
Did you try to use this v3 API in production?
https://github.com/cloudevents/sdk-go/tree/main/protocol/nats_jetstream/v3

Why do you think it is "OK" to create separate protocol binding object for each type of event?

If you don't see the issue, I will clarify:

The problem in the `cejsm.WithSendSubject` - actually this is not an Option, this is required setting!!!
You just can't send any event without setting this "Option"

And since this option not possible to set on Send - you MUST create Protocol for each type of event, since each event should send to separate subject.

### PR DESCRIPTION
**Pull request by kmpm**
I had some issues with a single subject regardless of event. Added a function to add an alternate subject via context.

This will also possibly close #1115

### CODE REVIEW

File: samples/nats_jetstream/v3/sender/main.go [hunk 1]
```diff
@@ -101,3 +103,11 @@ func createStream(url, streamName, subjectName string) error {
 	_, err = js.CreateOrUpdateStream(ctx, streamConfig)
 	return err
 }
+
+func buildSubject(base string, i int) string {
```
Comment (embano1) [inline samples/nats_jetstream/v3/sender/main.go:107]: nit: suggesting

```suggestion
func getRandomSubject(base string, i int) string {
```

File: protocol/nats_jetstream/v3/protocol.go [hunk 2]
```diff
@@ -19,6 +19,18 @@ import (
...
 
+type ctxKey string
+
+const (
+	ctxKeySubject ctxKey = "subject"
+)
+
+// WithSubject returns a new context with the subject set to the provided value.
+// This subject will be used when sending or receiving messages and overrides the default.
+func WithAltSubject(ctx context.Context, subject string) context.Context {
```
Comment (embano1) [inline protocol/nats_jetstream/v3/protocol.go:30]: Comment/API is misaligned, suggesting to go with:

```suggestion
func WithSubject(ctx context.Context, subject string) context.Context {
```

File: samples/nats_jetstream/v3/sender/main.go (hunk 1 above)
Comment (kmpm) [reply samples/nats_jetstream/v3/sender/main.go:107]: The subject is not random so that would not be a great name.

Comment (embano1) [reply samples/nats_jetstream/v3/sender/main.go:109]: Fair

**Review by duglin — APPROVED** [review]

**Comment by duglin** [comment]
Get we get a testcase?

**Comment by embano1** [comment]
Fair ask @duglin . @kmpm do you mind adding a test for coverage?

**Comment by kmpm** [comment]
`Protocol.Send` looks like a mess to mock in any meaningful way.
I could add some unit tests for Protocol.getSendSubject and also look at modifying the integration tests if it's enough?

**Comment by embano1** [comment]
Yeah sorry for the code base...I created a small unit test to verify the behavior, patch below

```patch
diff --git a/protocol/nats_jetstream/v3/protocol_test.go b/protocol/nats_jetstream/v3/protocol_test.go
new file mode 100644
index 0000000..b857a94
--- /dev/null
+++ b/protocol/nats_jetstream/v3/protocol_test.go
@@ -0,0 +1,85 @@
+/*
+ Copyright 2024 The CloudEvents Authors
+ SPDX-License-Identifier: Apache-2.0
+*/
+
+package nats_jetstream
+
+import (
+	"context"
+	"testing"
+
+	"github.com/cloudevents/sdk-go/v2/test"
+	"github.com/nats-io/nats.go"
+	"github.com/nats-io/nats.go/jetstream"
+)
+
+// mockJetStream implements jetstream.JetStream interface for testing
+type mockJetStream struct {
+	streamNameBySubjectFunc func(ctx context.Context, subject string) (string, error)
+	publishMsgFunc          func(ctx context.Context, msg *nats.Msg, opts ...jetstream.PublishOpt) (*jetstream.PubAck, error)
+	jetstream.JetStream
+}
+
+func (m *mockJetStream) StreamNameBySubject(ctx context.Context, subject string) (string, error) {
+	return m.streamNameBySubjectFunc(ctx, subject)
+}
+
+func (m *mockJetStream) PublishMsg(ctx context.Context, msg *nats.Msg, opts ...jetstream.PublishOpt) (*jetstream.PubAck, error) {
+	return m.publishMsgFunc(ctx, msg, opts...)
+}
+
+func TestSend(t *testing.T) {
+	tests := []struct {
+		name        string
+		sendSubject string
+		ctx         context.Context
+		wantSubject string
+	}{
+		{
+			name:        "using p.sendSubject",
+			sendSubject: "test.subject",
+			ctx:         context.Background(),
+			wantSubject: "test.subject",
+		},
+		{
+			name:        "using WithSubject",
+			sendSubject: "",
+			ctx:         WithSubject(context.Background(), "test.ctxSubject"),
+			wantSubject: "test.ctxSubject",
+		},
+		{
+			name:        "using WithSubject and p.sendSubject",
+			sendSubject: "test.subject",
+			ctx:         WithSubject(context.Background(), "test.ctxSubject"),
+			wantSubject: "test.ctxSubject",
+		},
+	}
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			mockJS := &mockJetStream{
+				streamNameBySubjectFunc: func(ctx context.Context, subject string) (string, error) {
+					if subject != tt.wantSubject {
+						t.Errorf("unexpected subject: got %s, want %s", subject, tt.wantSubject)
+					}
+					return "test-stream", nil
+				},
+				publishMsgFunc: func(ctx context.Context, msg *nats.Msg, opts ...jetstream.PublishOpt) (*jetstream.PubAck, error) {
+					if msg.Subject != tt.wantSubject {
+						t.Errorf("unexpected subject in publish: got %s, want %s", msg.Subject, tt.wantSubject)
+					}
+					return nil, nil
+				},
+			}
+
+			p := &Protocol{
+				jetStream:   mockJS,
+				sendSubject: tt.sendSubject,
+			}
+
+			msg := test.FullMessage()
+			_ = p.Send(tt.ctx, msg)
+		})
+	}
+}
```

**Comment by embano1** [comment]
@kmpm mind just copy and pasting the test so we can close this PR?

**Comment by kmpm** [comment]
@embano1 , I will fix it. Life got in the way. Thanks.

**Comment by embano1** [comment]
Thank you! I rebased onto the most recent commit. Can you please squash the test commit into one final commit? Should also fix the DCO warning (you need to `-s` sign-off **all** commits).

**Review by embano1 — APPROVED** [review]
Thank you!
