### PR TITLE
Helper function to create event from HTTP Request or Response

### LINKED ISSUE #766: Question, maybe add to documentation request: HTTP request to CloudEvent
Team, a bit of a newbie question, but I couldn't find the answer in the docs and maybe other people will have the same issue. 
Is there any simple way to transform an incoming HTTP request to a CloudEvent and fail with an error if the request doesn't contain the correct headers to be a CloudEvent? 

I am looking for something along the lines of `cloudevents.NewEvent(req)`, but I understand that this should come from the HTTP binding.  
I've found `protocol/http.NewMessageFromHttpRequest(req)` but again this seems to be transforming to an internal representation that is still one step away from being a CloudEvent. 

If there is one, it will be great to add that into the docs.. as most of the docs show how to create Handler functions that will automatically parse the HTTP request into a CloudEvent, but not the inner workings. 

If this is not recommended for some reason, it will be also good to add that to the docs.

### PR DESCRIPTION
**Pull request by grayside**
Fixes #766 

This PR provides two new functions: NewEventFromHttpRequest and NewEventFromHttpResponse. Both are added to v2/alias.go, and NewEventFromHttpRequest is also demonstrated in the README and docs.

I included HttpResponse because I saw the Message methods covered it. I included docs updates because I've visited the README and docs multiple times looking for this function. Happy to remove either if they are considered unnecessary or out of scope.

Creating this PR as a draft because the test coverage I've created routinely segfaults when it begins executing the transformation logic at:

https://github.com/cloudevents/sdk-go/blob/c623f8bfd7c3d7206f0aec5730460d137e3f42a8/v2/binding/to_event.go#L61

Here is an example of how this looks on my machine:

```text
go test -v -run TestNewEventFromHttpRequest
=== RUN   TestNewEventFromHttpRequest
=== RUN   TestNewEventFromHttpRequest/Event{"specversion":"1.0","id":"full-event-0","source":"http://example.com/source","type":"com.example.FullEvent","subject":"topic","datacontenttype":"text/json","dataschema":"http://example.com/schema","time":"2020-03-21T12:34:56.78Z","data":"hello","exurl":"http://example.com/source","extime":"2020-03-21T12:34:56.78Z","exbool":true,"exint":42,"exstring":"exstring","exbinary":"AAECAw=="}
=== RUN   TestNewEventFromHttpRequest/Event{"specversion":"1.0","id":"full-event-0","source":"http://example.com/source","type":"com.example.FullEvent","subject":"topic","datacontenttype":"text/json","dataschema":"http://example.com/schema","time":"2020-03-21T12:34:56.78Z","data":"hello","exurl":"http://example.com/source","extime":"2020-03-21T12:34:56.78Z","exbool":true,"exint":42,"exstring":"exstring","exbinary":"AAECAw=="}/Structured_encoding
--- FAIL: TestNewEventFromHttpRequest (0.00s)
    --- FAIL: TestNewEventFromHttpRequest/Event{"specversion":"1.0","id":"full-event-0","source":"http://example.com/source","type":"com.example.FullEvent","subject":"topic","datacontenttype":"text/json","dataschema":"http://example.com/schema","time":"2020-03-21T12:34:56.78Z","data":"hello","exurl":"http://example.com/source","extime":"2020-03-21T12:34:56.78Z","exbool":true,"exint":42,"exstring":"exstring","exbinary":"AAECAw=="} (0.00s)
        --- FAIL: TestNewEventFromHttpRequest/Event{"specversion":"1.0","id":"full-event-0","source":"http://example.com/source","type":"com.example.FullEvent","subject":"topic","datacontenttype":"text/json","dataschema":"http://example.com/schema","time":"2020-03-21T12:34:56.78Z","data":"hello","exurl":"http://example.com/source","extime":"2020-03-21T12:34:56.78Z","exbool":true,"exint":42,"exstring":"exstring","exbinary":"AAECAw=="}/Structured_encoding (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x141d695]

goroutine 6 [running]:
testing.tRunner.func1.2({0x151cfe0, 0x1982990})
	/Users/clipped/opt/go/libexec/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/Users/clipped/opt/go/libexec/src/testing/testing.go:1392 +0x39f
panic({0x151cfe0, 0x1982990})
	/Users/clipped/opt/go/libexec/src/runtime/panic.go:838 +0x207
github.com/cloudevents/sdk-go/v2/binding.Transformers.Transform(...)
	/Users/clipped/prototypes/snowpea-golang/sdk-go/v2/binding/transformer.go:34
github.com/cloudevents/sdk-go/v2/binding.ToEvent({0xc0000ec100?, 0x1466716?}, {0x1671030, 0xc0000207d0?}, {0xc00006ae78, 0x1, 0x0?})
	/Users/clipped/prototypes/snowpea-golang/sdk-go/v2/binding/to_event.go:65 +0x215
github.com/cloudevents/sdk-go/v2/protocol/http.NewEventFromHttpRequest(0x16707a0?)
	/Users/clipped/prototypes/snowpea-golang/sdk-go/v2/protocol/http/utility.go:19 +0x50
github.com/cloudevents/sdk-go/v2/protocol/http.TestNewEventFromHttpRequest.func1.1(0x0?)
	/Users/clipped/prototypes/snowpea-golang/sdk-go/v2/protocol/http/utility_test.go:42 +0xc6
testing.tRunner(0xc0002b81a0, 0xc0002ae1d0)
	/Users/clipped/opt/go/libexec/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/Users/clipped/opt/go/libexec/src/testing/testing.go:1486 +0x35f
exit status 2
```

### CODE REVIEW

**Comment by grayside** [comment]
A bit more detail: The line linked above is reached for events in binary encoding. When it happens, the transform statement is creating a transformer. Non-binary events are successfully created and returned earlier, and the Transformers slice is empty.

File: v2/protocol/http/utility.go [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+import (
+	"context"
+	nethttp "net/http"
+
+	"github.com/cloudevents/sdk-go/v2/binding"
+	"github.com/cloudevents/sdk-go/v2/event"
+)
+
+// NewEventFromHttpRequest returns an Event.
+func NewEventFromHttpRequest(req *nethttp.Request) (*event.Event, error) {
```
Comment (n3wscott) [inline v2/protocol/http/utility.go:17]: Golang style says this should be 
```suggestion
func NewEventFromHTTPRequest(req *nethttp.Request) (*event.Event, error) {
```

File: v2/protocol/http/utility.go [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+	msg := NewMessageFromHttpRequest(req)
+	return binding.ToEvent(context.Background(), msg, nil)
+}
+
+// NewEventFromHttpResponse returns an Event.
+func NewEventFromHttpResponse(resp *nethttp.Response) (*event.Event, error) {
```
Comment (n3wscott) [inline v2/protocol/http/utility.go:23]:
```suggestion
func NewEventFromHTTPResponse(resp *nethttp.Response) (*event.Event, error) {
```

File: v2/protocol/http/utility.go [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+	msg := NewMessageFromHttpResponse(resp)
```
Comment (n3wscott) [inline v2/protocol/http/utility.go:24]:
```suggestion
	msg := NewMessageFromHTTPResponse(resp)
```

File: v2/protocol/http/utility.go [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+	nethttp "net/http"
+
+	"github.com/cloudevents/sdk-go/v2/binding"
+	"github.com/cloudevents/sdk-go/v2/event"
+)
+
+// NewEventFromHttpRequest returns an Event.
+func NewEventFromHttpRequest(req *nethttp.Request) (*event.Event, error) {
+	msg := NewMessageFromHttpRequest(req)
+	return binding.ToEvent(context.Background(), msg, nil)
```
Comment (n3wscott) [inline v2/protocol/http/utility.go:19]: Found the issue,

```suggestion
	return binding.ToEvent(context.Background(), msg)
```

Because `ToEvent` is defined as `ToEvent(ctx context.Context, message MessageReader, transformers ...Transformer) (*event.Event, error)`, the iterator is attempting to call a nil transformer, note that transformers is a vararg and nil is a valid inner slice member. So when the code hits this:

```go
	for _, transformer := range t {
		err := transformer.Transform(r, w)
...
```

`transformer` is nil, because `t` has been created eq to `[]Transformer{nil}`, which is a slice of len 1, and `t[0]` happens to be `nil`.


To solve this, don't pass `nil` to the `vararg` (`, t ...Transformer`) param.

File: v2/protocol/http/utility.go (hunk 2 above)
Comment (grayside) [reply v2/protocol/http/utility.go:23]: I found `NewMessageFromHttpRequest` using camel case so I tried to track against that, happy to follow convention.

**Comment by grayside** [comment]
Thanks for the help troubleshooting. I'm going to clean this up to make it a non-draft.

Do you think there should be a passthru for transformers?

**Review by n3wscott — APPROVED** [review]
Looks like you just need to fix the signing and you will be good to go

**Comment by grayside** [comment]
I've signed off many of the commits, not sure how to fix it for all of them. Looking at the DCO doc, it looks like someone with write access can override. Can you point me to what my next step should be?

**Comment by n3wscott** [comment]
> I've signed off many of the commits, not sure how to fix it for all of them. Looking at the DCO doc, it looks like someone with write access can override. Can you point me to what my next step should be?

Thanks! I got it!
