### PR TITLE
Fix extensions encoding

### LINKED ISSUE #273: Extensions marshal to JSON broken
Blocking #270

When using `event.SetExtension` the marshal to JSON of an event including extensions with `URL`. E.g.:

```json
{"data":"hello","datacontenttype":"text/json","dataschema":"http://example.com/schema","exbinary":"AAECAw==","exbool":true,"exint":42,"exstring":"exstring","extime":"2020-03-21T12:34:56.78Z","exurl":{"Scheme":"http","Opaque":"","User":null,"Host":"example.com","Path":"/schema","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"id":"full-event-0","source":"http://example.com/source","specversion":"1.0","subject":"topic","time":"2020-03-21T12:34:56.78Z","type":"com.example.FullEvent"}
```

This is because `SetExtension` populates the underlying map not with wrapped types (provided by `types` module), but with go types. `net.URL` doesn't provide a meaningful marshal/unmarshal, which leads to this error.

Tests inside `event_marshal_test.go` are broken because they set correct values to the map directly, and not using `SetExtension` method.

## Reproducer

```go
func TestMarshalv1Ext(t *testing.T) {
	now := types.Timestamp{Time: time.Now().UTC()}
	sourceUrl, _ := url.Parse("http://example.com/source")
	source := &types.URIRef{URL: *sourceUrl}

	schemaUrl, _ := url.Parse("http://example.com/schema")
	schema := &types.URI{URL: *schemaUrl}

	testEvent := cloudevents.Event{
		Context: cloudevents.EventContextV1{
			Type:            "com.example.test",
			Source:          *source,
			DataSchema:      schema,
			ID:              "ABC-123",
			Time:            &now,
			DataContentType: cloudevents.StringOfApplicationJSON(),
		}.AsV1(),
		Data: DataExample{
			AnInt:   42,
			AString: "testing",
		},
	}

	testEvent.SetExtension("ex1", int32(42))
	testEvent.SetExtension("ex2", "testing")
	testEvent.SetExtension("ex4", schema)

	testCases := map[string]struct {
		event   cloudevents.Event
		want    []byte
		wantErr *string
	}{
		"v1.0 cased extensions": {
			event: testEvent,
			want: toBytes(map[string]interface{}{
				"specversion":     "1.0",
				"datacontenttype": "application/json",
				"data": map[string]interface{}{
					"a": 42,
					"b": "testing",
				},
				"id":   "ABC-123",
				"time": now.Format(time.RFC3339Nano),
				"type": "com.example.test",
				"ex1":  42,
				"ex2":  "testing",
				"ex4": "http://example.com/schema",
				"dataschema": "http://example.com/schema",
				"source":     "http://example.com/source",
			}),
		},
	}
	for n, tc := range testCases {
		t.Run(n, func(t *testing.T) {

			gotBytes, err := json.Marshal(tc.event)

			if tc.wantErr != nil || err != nil {
				if diff := cmp.Diff(*tc.wantErr, err.Error()); diff != "" {
					t.Errorf("unexpected error (-want, +got) = %v", diff)
				}
				return
			}

			// so we can understand the diff, turn bytes to strings
			want := string(tc.want)
			got := string(gotBytes)

			if diff := cmp.Diff(want, got); diff != "" {
				t.Errorf("unexpected event (-want, +got) = %v", diff)
			}
		})
	}
}
```

## Proposed actions

- `Extension` map should be populated with wrapped types, so they have the proper marshal/unmarshal function
- Tests inside `event_marshal_test.go` should use `SetExtension`

Bonus:

- make `Extension` map private, since there are accessors get, set, put

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Fixes #273 

## Breaking changes

* Now extension map doesn't contain (and should not contain anymore) `net.URL` & `time.Time` (and pointers). **Users that wants to modify this map manually should keep in mind these changes**
* Unmarshalled extension types from json are now coherent between different spec versions (they are always unmarshalled as go types)

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
cc @alanconway @n3wscott

File: pkg/binding/spec/spec.go [hunk 1]
```diff
@@ -108,7 +108,7 @@ func (v *version) SetAttribute(c ce.EventContextWriter, name string, value inter
 	name = strings.ToLower(name)
 	var err error
 	if strings.HasPrefix(name, v.prefix) { // Extension attribute
-		value, err = types.Validate(value)
+		value, err = types.ValidateAndWrap(value)
```
Comment (alanconway) [inline pkg/binding/spec/spec.go]: I would be inclined to just change the Validate() function rather than introduce a new function. The purpose of Validate() is to convert any "convertible" value into the "standard" Go form. As you've pointed out the "standard" form form URL and Time values should be the type wrappers since the native types lack proper marshalling - so you're fixing a bug in Validate(), rather than adding a new feature. I'd update the doc comments in the types package to reflect that.

File: pkg/cloudevents/event_marshal.go [hunk 2]
```diff
@@ -224,7 +224,11 @@ func (e *Event) JsonDecodeV02(body []byte, raw map[string]json.RawMessage) error
 		extensions := make(map[string]interface{}, len(raw))
 		for k, v := range raw {
 			k = strings.ToLower(k)
-			extensions[k] = v
+			var tmp interface{}
+			if err := json.Unmarshal(v, &tmp); err != nil {
+				return err
+			}
+			extensions[k] = tmp
```
Comment (alanconway) [inline pkg/cloudevents/event_marshal.go]: Should be ec.SetExtension(k, tmp) rather than direct map?

File: pkg/cloudevents/extensions.go [hunk 3]
```diff
@@ -27,4 +27,4 @@ func caseInsensitiveSearch(key string, space map[string]interface{}) (interface{
 	return nil, false
 }
 
-var IsAlphaNumericLowercaseLetters = regexp.MustCompile(`^[a-z0-9]+$`).MatchString
+var IsAlphaNumericLowercaseLetters = regexp.MustCompile(`^[a-zA-Z0-9]+$`).MatchString
```
Comment (alanconway) [inline pkg/cloudevents/extensions.go]: Rename: IsAlphaNumeric.

File: pkg/cloudevents/types/value.go [hunk 4]
```diff
@@ -131,6 +131,63 @@ func Validate(v interface{}) (interface{}, error) {
 	return nil, fmt.Errorf("invalid CloudEvents value: %#v", v)
 }
 
+// Validate v is a valid CloudEvents attribute value, convert it to one of:
+//     bool, int32, string, []byte, types.URI, types.URIRef, types.Timestamp
+func ValidateAndWrap(v interface{}) (interface{}, error) {
```
Comment (alanconway) [inline pkg/cloudevents/types/value.go]: See comment above - replace Validate() with this rather than adding a new function.

File: pkg/binding/spec/spec.go (hunk 1 above)
Comment (slinkydeveloper) [reply pkg/binding/spec/spec.go]: My bad, I thought `types.Validate` was used somewhere else

**Comment by alanconway** [comment]
Nope, I introduced it exactly for handling extension attributes. Thanks for
fixing it up!

**Comment by slinkydeveloper** [comment]
Any idea why the ci fails? I've tried to run go fmt but there are no changes

**Comment by alanconway** [comment]
> Any idea why the ci fails? I've tried to run go fmt but there are no changes

Nope, go fmt passed for me too.  You might be able to fix the CI script so it shows the output by hacking on .circleci/config.yml

**Comment by slinkydeveloper** [comment]
The problem was inside the CI script. To check if code is formatted, there is a check on the output of `go fmt`, if there isn't any, then the step succeds. The problem is that `go fmt` could potentially print that is solving dependencies, like:

```
#!/bin/bash -eo pipefail
go fmt ./...

go: finding github.com/pkg/errors v0.8.1
```

Disabling go modules while running `go fmt` does the trick.

BTW I haven't added any new dependency

File: pkg/cloudevents/extensions.go [hunk 5]
```diff
@@ -27,4 +27,4 @@ func caseInsensitiveSearch(key string, space map[string]interface{}) (interface{
 	return nil, false
 }
 
-var IsAlphaNumericLowercaseLetters = regexp.MustCompile(`^[a-z0-9]+$`).MatchString
+var IsAlphaNumeric = regexp.MustCompile(`^[a-zA-Z0-9]+$`).MatchString
```
Comment (n3wscott) [inline pkg/cloudevents/extensions.go]: the spec says only lowercase are supported.

Comment (n3wscott) [reply pkg/cloudevents/extensions.go]:
```markdown
CloudEvents attribute names MUST consist of lower-case letters ('a' to 'z') or digits ('0' to '9') from the ASCII character set. Attribute names SHOULD be descriptive and terse and SHOULD NOT exceed 20 characters in length.
```

https://github.com/cloudevents/spec/blob/master/spec.md#attribute-naming-convention

Comment (slinkydeveloper) [reply pkg/cloudevents/extensions.go]: Yes but `setExtension` make it lowercase https://github.com/cloudevents/sdk-go/blob/2676232a051b22008883dc9b95906842f017398b/pkg/cloudevents/eventcontext_v1.go#L82

Comment (slinkydeveloper) [reply pkg/cloudevents/extensions.go]: And this also makes the behaviour consistent with other context implementations where this is not required

**Comment by n3wscott** [comment]
LGTM!!
