### PR TITLE
Fix comparison to nil interface

### LINKED ISSUE #477: GET requests or bad payloads make the SDK panic
The receiver panics when receiving a GET request of empty payload.

Given this client
```go
func main() {
    cli, _ := cloudevents.NewDefaultClient()
    cli.StartReceiver(ctx, func(cloudevents.Event) {})
}
```

just `curl localhost:8080`.

<details><summary>📄 error trace</summary>

```
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7b2946]

goroutine 19 [running]:
github.com/cloudevents/sdk-go/v2/protocol/http.(*Message).Finish(0x0, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.0.0-!r!c1/protocol/http/message.go:151 +0x26
github.com/cloudevents/sdk-go/v2/client.(*receiveInvoker).Invoke.func1(0xd91c20, 0x0, 0xc00006de78)
        /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.0.0-!r!c1/client/invoker.go:41 +0x47
panic(0xba6860, 0x128d010)
        /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/cloudevents/sdk-go/v2/protocol/http.(*Message).ReadEncoding(0x0, 0xc000020000)
        /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.0.0-!r!c1/protocol/http/message.go:81 +0x5
github.com/cloudevents/sdk-go/v2/binding.ToEvent(0xd91c60, 0xc0000ae000, 0x7fce984681a0, 0x0, 0x0, 0x0, 0x0, 0xc00006ddbc, 0x2, 0x2)
        /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.0.0-!r!c1/binding/to_event.go:28 +0x52
github.com/cloudevents/sdk-go/v2/client.(*receiveInvoker).Invoke(0xc00009e560, 0xd91c60, 0xc0000ae000, 0xd91c20, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.0.0-!r!c1/client/invoker.go:46 +0xfc
github.com/cloudevents/sdk-go/v2/client.(*ceClient).StartReceiver(0xc0000ce0a0, 0xd91c60, 0xc0000ae000, 0xb69e00, 0xcc3008, 0x0, 0x0)
        /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.0.0-!r!c1/client/client.go:218 +0x287
github.com/cloudevents/sdk-go/v2/client.(*obsClient).StartReceiver(0xc00009e540, 0xd91c60, 0xc0000ae000, 0xb69e00, 0xcc3008, 0x0, 0x0)
        /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.0.0-!r!c1/client/client_observed.go:93 +0xac
main.(*handler).Start.func1(0xc0000dc0c0, 0xc0000b03d0, 0xd91c60, 0xc0000ae000)
        /go/src/github.com/triggermesh/myproject/cmd/mycmdtarget/main.go:85 +0x63
created by main.(*handler).Start
        /go/src/github.com/triggermesh/myproject/cmd/mycmdtarget/main.go:84 +0x7a
exit status 2
```

</details>

The culprit is here:

https://github.com/cloudevents/sdk-go/blob/0fc16e13d87f0f2b1c99ec41183e35c0e68b6b5c/v2/binding/to_event.go#L23-L26

This comparison is `false` even when the request contains no payload.

---

edit: I observe the same result by sending valid payloads with a "bad" or missing `Content-Type` header:

```
$ curl -XPOST -H "Content-Type: application/json" localhost:8080/ -d'{
    "specversion" : "1.0",
    "type" : "com.example.someevent",
    "source" : "/mycontext",
    "id" : "A234-1234-1234",
    "time" : "2018-04-05T17:31:00Z",
    "comexampleextension1" : "value",
    "comexampleothervalue" : 5,
    "datacontenttype" : "text/xml",
    "data" : "<much wow=\"xml\"/>"
}'

// missing "+json" in the header -> boom
```

### PR DESCRIPTION
**Pull request by antoineco**
Fix an issue where comparing a nil Message interface to nil would always return `false`, causing the receiver to crash.

Also respond with an error instead of OK when the message encoding can't be determined.

```
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Wed, 29 Apr 2020 10:18:26 GMT
Content-Length: 49

Cannot read CloudEvent: unknown Message encoding
```

Fixes #477

### CODE REVIEW

File: v2/protocol/http/protocol.go [hunk 1]
```diff
@@ -201,7 +201,12 @@ func (p *Protocol) Respond(ctx context.Context) (binding.Message, protocol.Respo
 		if !ok {
 			return nil, nil, io.EOF
 		}
+
+		if in.msg == nil {
+			return nil, in.respFn, in.err
+		}
```
Comment (antoineco) [inline v2/protocol/http/protocol.go:207]: An alternative would be to use reflection to compare `message` to `nil` here: https://github.com/cloudevents/sdk-go/blob/0fc16e13d87f0f2b1c99ec41183e35c0e68b6b5c/v2/binding/to_event.go#L23-L26

I believe we should avoid using reflection whenever possible.

Comment (slinkydeveloper) [reply v2/protocol/http/protocol.go:207]: Fully agree!

File: v2/protocol/http/protocol.go [hunk 2]
```diff
@@ -218,6 +223,7 @@ type msgErr struct {
 func (p *Protocol) ServeHTTP(rw http.ResponseWriter, req *http.Request) {
 	m := NewMessageFromHttpRequest(req)
 	if m == nil || m.ReadEncoding() == binding.EncodingUnknown {
+		http.Error(rw, fmt.Sprintf("Cannot read CloudEvent: %s", binding.ErrUnknownEncoding), http.StatusBadRequest)
```
Comment (slinkydeveloper) [inline v2/protocol/http/protocol.go:226]: Can we address this problem in the https://github.com/cloudevents/sdk-go/pull/480?

Comment (slinkydeveloper) [reply v2/protocol/http/protocol.go:226]: Ah ok i see now, the problem is different from #480.

Anyway, I think this is a bad change because `EncodingUnknown` happens in several situations, even on a simple get request without any parameter/cloudevent: eg ff the receiver just wants to return events, without expecting to receive any, the encoding of the received event will be unknown. What i'm trying to say is: at the protocol level, i think we should not just fail the request, this should be up to the protocol user. If you experienced this problem using the client, then we need to address the problem in a different way on the client code.

Comment (antoineco) [reply v2/protocol/http/protocol.go:226]: What I want to avoid here is external clients (not CE) sending random requests to the endpoint and crashing it. The HTTP response is to me a plus, just to play nice with the HTTP protocol. If that's not fine with the CE contract I'm happy to remove this.

Still, I'm a bit puzzled when I see a request fail with 200 and no payload in general.

Comment (antoineco) [reply v2/protocol/http/protocol.go]: Removed in 49fae7d

**Comment by antoineco** [comment]
@slinkydeveloper general question about the case where I send a valid event, but the `Content-Type` header is set to e.g. `Content-Type: application/foo`. Is it acceptable to just respond with `200` like we do?

**Comment by antoineco** [comment]
> Can you try to provide a test to check if the problem you experienced doesn't happen again?

On it.

**Comment by slinkydeveloper** [comment]
> Clearly the event was dropped, but from the perspective of the client we're just fine.

I suppose yes, how do i know that the body content is an event if the content-type is not `application/cloudevents+json`? Maybe `application/foo` uses the same stuff of a cloudevent :smile: .

Apart the jokes, i think this is a perfectly fine behaviour for the `Client`. The answer for these more "complex" use cases where you mix cloudevent and non-cloudevents is: use directly the `http.Protocol` and handle manually the encoding unknown, parsing the eventual non cloudevent request as you prefer

**Comment by antoineco** [comment]
> Maybe `application/foo` uses the same stuff of a cloudevent

Sure, but our endpoint handles `application/cloudevents+json` exclusively, so it should notify the client (_any_ HTTP client) back if it doesn't accept the document type, otherwise the implementation doesn't satisfy [RFC2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.16).

---

I [added a test](https://github.com/cloudevents/sdk-go/compare/49fae7d70b0040ced37065ad78954a49f0a7b526..5341e719805bd33503ba5d9bf8cc3cb1fe766b4b). Here's the output with the change commented:

```
--- FAIL: TestRespond (0.01s)
    --- FAIL: TestRespond/TODO (0.01s)
        protocol_test.go:192:
                Error Trace:    protocol_test.go:192
                Error:          Expected value not to be nil.
                Test:           TestRespond/TODO
                Messages:       Nil interface compares to nil
        protocol_test.go:196: unexpected diff (-want, +got) =   interface{}(
            +   (*http.Message)(nil),
              )
FAIL
FAIL    github.com/cloudevents/sdk-go/v2/protocol/http  2.046s
FAIL
```

**Comment by slinkydeveloper** [comment]
> Sure, but our endpoint handles application/cloudevents+json exclusively, so it should notify the client (any HTTP client) back if it doesn't accept the document type

That's a really interesting point here, i never thought about that... I feel this kind of problem should be brought at spec level, because it gives an hint on how to parse the event https://github.com/cloudevents/spec/blob/v1.0/http-protocol-binding.md#3-http-message-mapping but it also states _Otherwise it defaults to binary mode._ which is clearly what we don't do in the sdk, because in the end the user needs a distinction between event/non event. So the criteria on replying with a content type not supported is interesting, i think you should open an issue on the spec about that

**Comment by antoineco** [comment]
@slinkydeveloper I opened #483 for discussions.

File: v2/protocol/http/protocol.go (hunk 1 above)
Comment (n3wscott) [reply v2/protocol/http/protocol.go:207]: we use reflection in the client invoker but that is only processed once at startup.

File: v2/protocol/http/protocol.go [hunk 3]
```diff
@@ -201,7 +201,12 @@ func (p *Protocol) Respond(ctx context.Context) (binding.Message, protocol.Respo
 		if !ok {
 			return nil, nil, io.EOF
 		}
+
+		if in.msg == nil {
+			return nil, in.respFn, in.err
```
Comment (n3wscott) [inline v2/protocol/http/protocol.go:206]: ah, we got caught by the typed nil in go... nice. 👍

**Comment by n3wscott** [comment]
> $ curl -D- -H "Content-Type: application/foo" localhost:8080/ -d'{
>     "specversion" : "1.0",
>     "type" : "com.example.someevent",
>     "source" : "/mycontext",
>     "id" : "A234-1234-1234",
>     "time" : "2018-04-05T17:31:00Z",
>     "comexampleextension1" : "value",
>     "comexampleothervalue" : 5,
>     "datacontenttype" : "text/xml",
>     "data" : "<much wow=\"xml\"/>"
> }'
> HTTP/1.1 200 OK
> Date: Wed, 29 Apr 2020 10:55:59 GMT
> Content-Length: 0

this should be a 400 return I think.

File: v2/protocol/http/protocol.go (hunk 3 above)
Comment (antoineco) [reply v2/protocol/http/protocol.go:206]: Hehe looks like it, a very vicious one!

**Comment by antoineco** [comment]
@n3wscott so are you fine with me reverting that second commit?

File: v2/protocol/http/protocol.go [hunk 4]
```diff
@@ -223,7 +223,6 @@ type msgErr struct {
 func (p *Protocol) ServeHTTP(rw http.ResponseWriter, req *http.Request) {
 	m := NewMessageFromHttpRequest(req)
 	if m == nil || m.ReadEncoding() == binding.EncodingUnknown {
-		http.Error(rw, fmt.Sprintf("Cannot read CloudEvent: %s", binding.ErrUnknownEncoding), http.StatusBadRequest)
```
Comment (n3wscott) [inline v2/protocol/http/protocol.go]: if it returns anything it should be in the form of a cloudevent

File: v2/protocol/http/protocol.go [hunk 5]
```diff
@@ -223,7 +223,6 @@ type msgErr struct {
...
 		p.incoming <- msgErr{msg: nil, err: binding.ErrUnknownEncoding}
 		return // if there was no message, return.
```
Comment (n3wscott) [inline v2/protocol/http/protocol.go]: we should set the rw.Status to 415 as you are saying

File: v2/protocol/http/protocol.go (hunk 2 above)
Comment (n3wscott) [reply v2/protocol/http/protocol.go]: not crashing sounds like a good thing 😄

**Comment by n3wscott** [comment]
> i think this is a perfectly fine behaviour for the `Client`.

Totally. But if the request ends up in the sdk handler and it can not process it, it should reject it and tell the caller that the request was bad. 

We should do this for GET methods too if we are not a pull based protocol, as a follow up.

File: v2/protocol/http/protocol.go (hunk 5 above)
Comment (slinkydeveloper) [reply v2/protocol/http/protocol.go]: I don't think so @n3wscott, what about an empty request?

Comment (slinkydeveloper) [reply v2/protocol/http/protocol.go]: that's why imo this shouldn't fail, even better not here in the protocol where a protocol user could decide to handle the encoding unknown case

Comment (antoineco) [reply v2/protocol/http/protocol.go:228]: done

File: v2/protocol/http/protocol.go (hunk 4 above)
Comment (antoineco) [reply v2/protocol/http/protocol.go]: @n3wscott I'd appreciate some pointer or example to set all the attributes and format correctly. Do you do that in other places?

File: v2/protocol/http/protocol.go (hunk 5 above)
Comment (n3wscott) [reply v2/protocol/http/protocol.go:228]: slinky has a good point, we use to have a converter feature that would allow us to try to convert or wrap a bad message into a cloudevent and then deliver that to a consumer, how could we allow that use case and still do this if no other option was available?

File: v2/protocol/http/protocol.go [hunk 6]
```diff
@@ -218,6 +223,7 @@ type msgErr struct {
 func (p *Protocol) ServeHTTP(rw http.ResponseWriter, req *http.Request) {
 	m := NewMessageFromHttpRequest(req)
 	if m == nil || m.ReadEncoding() == binding.EncodingUnknown {
+		http.Error(rw, "Cannot read CloudEvent: "+binding.ErrUnknownEncoding.Error(), http.StatusUnsupportedMediaType)
```
Comment (n3wscott) [inline v2/protocol/http/protocol.go:226]: ok sorry, lets hold off on this change until we decide on a fix in #483 

There is value in letting the client level know that an event was attempted and it failed... the user or client could choose to fix the event for the consumer. So let's hold off on http.Error for now. Sorry for the flip flopping.... The reason is just because we are trying to not put too many runtime choices at the protocol level.

Comment (antoineco) [reply v2/protocol/http/protocol.go]: Removed

**Comment by slinkydeveloper** [comment]
Thanks for your contribution! @antoineco
